# Generated by Django 3.0.1 on 2020-02-18 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demoer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('lead', models.CharField(max_length=50)),
                ('need_shadow', models.BooleanField()),
                ('three_pillar', models.BooleanField()),
                ('apm', models.BooleanField()),
                ('logs', models.BooleanField()),
                ('custom_metrics', models.BooleanField()),
                ('notes', models.CharField(max_length=250)),
                ('preferred_topic', models.CharField(blank=True, max_length=50, null=True)),
                ('max_mrr', models.IntegerField(choices=[(1400, '1400'), (2500, '2500'), (3500, '3500'), (5000, '5000')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
