# Generated by Django 3.0.1 on 2020-03-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoer',
            name='region',
            field=models.CharField(choices=[('US-EAST', 'US-East'), ('US-WEST', 'US-West'), ('EMEA', 'EMEA'), ('APAC', 'APAC')], max_length=30),
        ),
    ]
