# Generated by Django 3.0.1 on 2020-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoer',
            name='preferred_topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
